services:
    productdb:
        container_name: productdb
        restart: always
        ports:
            - "27018:27017"
        volumes:
        - mongo_data:/data/db

    catalog.api:
        container_name: product.api
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "DatabaseSettings__ConnectionString=mongodb://productdb:27017"
          - "DatabaseSettings__DatabaseName=productDb"
          - "DatabaseSettings__CollectionName=Products"
          - "DatabaseSettings__CollectionName=ProductBrands"
          - "DatabaseSettings__CollectionName=ProductTypes" 
        depends_on:
            - productdb
        ports:
          - "7000:80"